In [1]:
import geopandas as gpd

In [3]:
gpd = gpd.read_file('dados/subestacoes/Subestações_-_Base_Existente.shp')

In [4]:
gpd

,Nome,Concession,Ano_Opera,Tensao,longitude,latitude,CD_MUN,geometry
0,SE Anhanguera,CTEEP - Companhia de Transmissão de Energia El...,-,345/230/88,-46.768299,-23.493160,None,POINT (-46.7683 -23.49316)
1,SE Bandeirantes,CTEEP - Companhia de Transmissão de Energia El...,-,"345/88/34,5",-46.692243,-23.598873,None,POINT (-46.69224 -23.59887)
2,SE Centro - CTR,CTEEP - Companhia de Transmissão de Energia El...,-,230/88/20,-46.648299,-23.536800,None,POINT (-46.6483 -23.5368)
3,SE Centro - CTT,CTEEP - Companhia de Transmissão de Energia El...,-,230,-46.721444,-23.513014,None,POINT (-46.72144 -23.51301)
4,SE Interlagos,CTEEP - Companhia de Transmissão de Energia El...,-,345/230,-46.681419,-23.710087,None,POINT (-46.68142 -23.71009)
5,SE Miguel Reale,CTEEP - Companhia de Transmissão de Energia El...,-,345/88/20,-46.625280,-23.562452,None,POINT (-46.62528 -23.56245)
6,SE Milton Fornasaro,CTEEP - Companhia de Transmissão de Energia El...,-,345/88,-46.751953,-23.528194,None,POINT (-46.75195 -23.52819)
7,SE Norte,CTEEP - Companhia de Transmissão de Energia El...,-,345/88,-46.558311,-23.483141,None,POINT (-46.55831 -23.48314)
8,SE Piratininga,CTEEP - Companhia de Transmissão de Energia El...,-,230/88,-46.677405,-23.698736,None,POINT (-46.6774 -23.69874)
9,SE Piratininga 2,IEP - INTERLIGAÇÃO ELÉTRICA PINHEIROS S.A,2011,345/88,-46.682747,-23.705646,None,POINT (-46.68275 -23.70565)
10,SE Pirituba,CTEEP - Companhia de Transmissão de Energia El...,-,230/88,-46.709394,-23.500973,None,POINT (-46.70939 -23.50097)
11,SE Ramom Reberte Filho,CTEEP - Companhia de Transmissão de Energia El...,-,345/88,-46.523561,-23.579408,None,POINT (-46.52356 -23.57941)
12,SE Sul,CTEEP - Companhia de Transmissão de Energia El...,-,345/88,-46.521007,-23.699379,None,POINT (-46.52101 -23.69938)
13,SE Leste,CTEEP - Companhia de Transmissão de Energia El...,-,345/88,-46.468532,-23.595511,None,POINT (-46.46853 -23.59551)
14,SE Xavantes,CTEEP - Companhia de Transmissão de Energia El...,-,345,-46.723389,-23.658088,None,POINT (-46.72339 -23.65809)
15,SE UTE Fernando Gasparian,PETROBRAS - Petroleo Brasileiro S.A,-,"230/13,8",-46.678704,-23.699338,None,POINT (-46.6787 -23.69934)
16,SE UTE Piratininga,BSE - Baixada Santista Energia S.A.,1954,230,-46.677782,-23.699596,None,POINT (-46.67778 -23.6996)